### ISSUE TITLE
Something Wrong...

### ISSUE THREAD

**Issue by Enderman-Teleporting** [AHilyard/CooperativeAdvancements#2]
My friend made a lot of advancements but I got none.
I am quite sure I got all the dependencies okay.
running on 1.19 fabric

**Comment by Enderman-Teleporting** [comment]
However, the server did not crash and it shows that the mod is loaded properly(together with the dependencies)
![SharedScreenshot](https://user-images.githubusercontent.com/100068319/178505747-60a0b8f8-4b9f-4831-95ea-6304ed82e984.jpg)

**Comment by Enderman-Teleporting** [comment]
Or do the players who want to share the advancements have to be online (Most of my friends simply uses offline mode cuz they don't have an account)

**Comment by Enderman-Teleporting** [comment]
if so, i hope that it can be improved if possible
thanks

**Comment by AHilyard** [comment]
Hey there, advancements are shared between online players on login and whenever someone makes progress on an advancement.  Are you saying you're not playing at the same time as your friend or something else?

**Comment by Enderman-Teleporting** [comment]
> Hey there, advancements are shared between online players on login and whenever someone makes progress on an advancement. Are you saying you're not playing at the same time as your friend or something else?

emm i mean my friends do not have a legitimate account as i do and they use launchers such as pcl and hmcl (can be found in github). is that the reason why i cannot share advancements with them on my server?

**Comment by Enderman-Teleporting** [comment]
ive set online mod false

**Comment by AHilyard** [comment]
Sorry, I can't support illegitimate accounts.  Still, if you are playing at the same time and the mod is installed on the server it should share advancements.
